version: '3.8'

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development 
    ports:
      - "${SCRAPER_PORT}:8000"
    networks:
      - backend

networks:
  backend:
    external:
      name: flaskapp

