version: '3.8'

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development 
    ports:
      - "${SCRAPER_PORT}:${SCRAPER_PORT}"
    networks:
      - backend
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend

networks:
  backend:
    external:
      name: flaskapp
      
volumes:
  mongodb-data:
